### ISSUE TITLE
Upgrade with wso2 v.5.9

### ISSUE THREAD

**Issue by marcoranica94** [nilasini/CustomPermissionClaimHandler#1]
Currently in wso2 the file to be modified to customize the claims is deployment.toml.  Not application-authentication.xml 

I suggest changing the readme in point 3.

**https://is.docs.wso2.com/en/5.9.0/develop/writing-a-custom-claim-handler/#writing-the-custom-claim-handler**

```
[authentication.framework.extensions] 
claim_handler="com.wso2.sample.claim.handler.CustomClaimHandler" 
```

Thanks. Bye

**Comment by nilasini** [comment]
Fixed. Thanks for mentioning this.
